version: 3

images:
  base_image:
    name: quay.io/fedora/fedora:42
dependencies:
  system:
  - python3
  - python3-pip
  - openssh-clients
  - sshpass
  - wireguard-tools
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
    - name: ansible.posix
    - name: ansible.utils
    - name: containers.podman
    - name: community.general
    - name: community.crypto
  python:
    - passlib

additional_build_files:
  - src: ../collections/ansible_collections/scroker/home_lab
    dest: home_lab_collection

additional_build_steps:
  prepend_base:
    - RUN dnf install -y python3 python3-pip && dnf clean all
  append_galaxy:
    - COPY _build/home_lab_collection /usr/share/ansible/collections/ansible_collections/scroker/home_lab