---
- name: Configure Fedora server
  become: true
  block:
    - name: Check if firewalld is present and running
      ansible.builtin.service_facts:

    - name: Install necessary package
      ansible.builtin.dnf:
        name:
          - cockpit
          - cockpit-podman
          - cockpit-selinux
        state: present 

    - name: Make sure cockpit is enabled and running
      ansible.builtin.systemd_service:
        name: cockpit
        state: started
        enabled: true

    - name: Make sure cockpit.socket is enabled and running
      ansible.builtin.systemd_service:
        name: 'cockpit.socket'
        state: started
        enabled: true

    - name: Permit traffic in default zone on service cockpit
      ansible.posix.firewalld:
        service: cockpit
        zone: '{{ item }}'
        permanent: true
        immediate: true
        state: enabled
      loop: '{{ cockpit.zones }}'
      when: >-
        cockpit.zones is defined and
        ansible_facts.services['firewalld.service'].state is defined and
        ansible_facts.services['firewalld.service'].state == 'running'    
      notify:
        - Restart firewalld service