---
- name: Configure Fedora server
  become: true
  block:
  - name: Install necessary package
    ansible.builtin.dnf:
      name:
        - cockpit
        - cockpit-podman
        - cockpit-selinux
      state: present 
  
  - name: Make sure cockpit is enabled and running
    ansible.builtin.systemd_service:
      name: cockpit
      state: started
      enabled: true

  - name: Make sure cockpit.socket is enabled and running
    ansible.builtin.systemd_service:
      name: 'cockpit.socket'
      state: started
      enabled: true
  
  - name: Permit traffic in default zone on service cockpit
    ansible.posix.firewalld:
      service: cockpit
      zone: '{{ cockpit_zone }}'
      permanent: true
      immediate: true
      state: enabled
    when: >-
      cockpit_zone is defined