---
- name: Configure Fedora server
  become: true
  block:
  - name: Install necessary package
    ansible.builtin.dnf:
      name:
        - cockpit
        - cockpit-podman
        - cockpit-selinux
      state: present 
  - name: Make sure cockpit is enabled and running
    ansible.builtin.systemd_service:
      state: started
      enabled: true
      name: 'cockpit.socket'
  - name: Permit traffic in default zone on service cockpit
    ansible.posix.firewalld:
      service: cockpit
      zone: internal
      permanent: true
      immediate: true
      state: enabled