- name: Install Certbot
  ansible.builtin.dnf:
    name:
      - epel-release
      - nginx
      - certbot
      - python3-certbot-apache
    state: present
  when: nginx_cloud_install is false

- name: Check if firewalld is present and running
  ansible.builtin.service_facts:

- name: Start and enable Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  when: nginx_cloud_install is false

- name: Copy nginx base configuration
  ansible.builtin.copy:
    src: nginx/
    dest: "{{ nginx_config_folder }}"
    owner: "{{ nginx_config_folder_owner }}"
    group: "{{ nginx_config_folder_group }}"
    mode: "{{ nginx_config_folder_mode }}"
  when: nginx_cloud_install is true

- name: Copy nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_folder }}/nginx.conf"
    owner: "{{ nginx_config_folder_owner }}"
    group: "{{ nginx_config_folder_group }}"
    mode: "{{ nginx_config_folder_mode }}"

- name: Create nginx resources configuration
  ansible.builtin.template:
    src: resource.conf.j2
    dest: "{{ nginx_config_folder }}/conf.d/{{ item.server_name }}.conf"
    owner: "{{ nginx_config_folder_owner }}"
    group: "{{ nginx_config_folder_group }}"
    mode: "{{ nginx_config_folder_mode }}"
  when: nginx_resources is defined
  loop: '{{ nginx_resources }}'

- name: Restart nginx service
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: nginx_cloud_install is false

- name: Configure firewall to allow http and https
  when: >-
    ansible_facts.services['firewalld.service'].state is defined and
    ansible_facts.services['firewalld.service'].state == 'running'
  notify:
    - Restart firewalld service
  block:
    - name: Permit traffic on 80 port
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled

    - name: Permit traffic on 443 port
      ansible.posix.firewalld:
        service: https
        permanent: true
        immediate: true
        state: enabled
