---
- name: Setup dnsmasq container
  hosts: vpnserver
  pre_tasks:
    - name: Create dnsmasq config directory
      become: true
      ansible.builtin.file:
        path: "{{ dnsmasq_config_dir | default('/etc/dnsmasq') }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Deploy dnsmasq config
      become: true
      ansible.builtin.template:
        src: dnsmasq.conf.j2
        dest: "{{ dnsmasq_config_dir | default('/etc/dnsmasq') }}/dnsmasq.conf"
        owner: root
        group: root
        mode: "0644"

    - name: Enable service facts
      become: true
      ansible.builtin.service_facts:

    - name: Permit DNS traffic on firewall
      become: true
      ansible.posix.firewalld:
        service: dns
        zone: "{{ dnsmasq.zone }}"
        permanent: true
        immediate: true
        state: enabled
      when: >-
        ansible_facts['os_family'] == "RedHat" and
        ansible_facts.services['firewalld.service'].state is defined and
        ansible_facts.services['firewalld.service'].state == 'running'
  roles:
    - scroker.home_lab.container_runtime
