---
- name: Restart nginx service
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart firewalld service
  become: true
  ansible.builtin.service:
    name: firewalld
    state: restarted