FROM registry.access.redhat.com/ubi8/nginx-120 as build
RUN mkdir certs
RUN openssl dhparam \
        -out dhparam.pem 4096
RUN openssl req -x509 \
        -nodes \
        -days 365 \
        -newkey rsa:2048 \
        -addext "subjectAltName = DNS:localhost" \
        -keyout certs/nginx-selfsigned.key \
        -out certs/nginx-selfsigned.crt \
        -subj "/C=IT/ST=Lazio/L=Roma/O=Giorgio Dramis/OU=Giorgio Dramis/CN=localhost"

FROM registry.access.redhat.com/ubi8/nginx-120

USER root
RUN mkdir /etc/ssl/private
COPY --from=build /opt/app-root/src/certs/* /etc/ssl/private/
RUN chown -R 1001:0 /etc/ssl/private
COPY --from=build /opt/app-root/src/dhparam.pem /etc/nginx/dhparam.pem
COPY ssl-params.conf /etc/nginx/snippets/ssl-params.conf
COPY self-signed.conf /etc/nginx/snippets/self-signed.conf

USER 1001
RUN nginx -t
COPY ./nginx.conf "${NGINX_CONF_PATH}"
CMD nginx -g "daemon off;"

