---
- name: Install and codfigure firewalld
  become: true
  block:
  
  - name: Install necessary package
    ansible.builtin.dnf:
      name:
        - firewalld
        - python3-firewall
      state: present

  - name: Make sure firewalld is enabled and running
    ansible.builtin.systemd_service:
      state: started
      enabled: true
      name: firewalld
      masked: false