---
- name: Configure firewalld for dnsmasq
  become: true
  block:
    - name: Permit traffic on wireguard service
      ansible.posix.firewalld:
        service: wireguard
        zone: '{{ dnsmasq.zone }}'
        permanent: true
        immediate: true
        state: enabled