---
- name: Install and configure dnsmasq 
  become: true
  block: 

  - name: Enable service facts on host
    ansible.builtin.service_facts:

  - name: Install required packages
    ansible.builtin.dnf:
      name: dnsmasq
      state: present

  - name: Apply dnsmasq config template
    ansible.builtin.template:
      src: dnsmasq.conf.j2
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: 0644
  
  - name: Start dnsmasq service
    ansible.builtin.service:
      name: dnsmasq
      enabled: true
      state: started

  - name: Disable systemd-resolved service
    ansible.builtin.service:
      name: systemd-resolved
      state: stopped
      enabled: false
    when: >-
      ansible_facts.services['systemd-resolved.service'].state is defined and
      ansible_facts.services['systemd-resolved.service'].state == 'running'

  - ansible.builtin.import_tasks: firewalld.yml
    when: >-
      ansible_facts.services['firewalld.service'].state is defined and
      ansible_facts.services['firewalld.service'].state == 'running'