---
- name: Configure sysctl to forward ipv4 ipv6 
  become: true
  block:
  - name: Allow ipv4 forward
    ansible.builtin.lineinfile:
      path: /etc/sysctl.conf
      line: net.ipv4.ip_forward = 1

  - name: Allow ipv4 forward
    ansible.builtin.lineinfile:
      path: /etc/sysctl.conf
      line: net.ipv6.conf.all.forwarding = 1

  - name: Reload sysctl conf
    ansible.builtin.command:
      cmd: sysctl -p